// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyvfxwutltzuaeeuvflg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dmZ4d3V0bHR6dWFlZXV2ZmxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDc3NDgsImV4cCI6MjA3NDUyMzc0OH0.-8ZKOz48EU6vVN6S-0I9GTj7jJfIPetDU6urn8xn2m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});